FROM oven/bun:1.2.18-alpine AS builder

WORKDIR /app

ARG VITE_TURNSTILE_SITE_KEY
ENV VITE_TURNSTILE_SITE_KEY=$VITE_TURNSTILE_SITE_KEY

COPY package.json bun.lock* ./
RUN bun install

COPY . .
RUN bun run build:client

FROM nginx:alpine

COPY ./nginx/frontend.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80