services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: games-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '4200:4200'

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: games-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - '80:80'